Algoritmo "Calculo Imposto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Daniela Salgado
// Data atual  : 23/11/2025
Var

     preco, imposto : real

Inicio

     Escreval("Qual é o preço do produto?")
     leia(preco)
     
     imposto <- (preco * 60) / 100
     
     Escreval
     Escreval("O imposto será US$ ", imposto)

Fimalgoritmo