Algoritmo "Combinações"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Daniela Salgado
// Data atual  : 28/11/2025
Var

   contador1, contador2 : inteiro

Inicio

   Para contador1 := 1 ate 3 faca
      Para contador2 := 1 ate 3 faca
        Escreval ( contador1, contador2)
      FimPara
   FimPara

Fimalgoritmo