Algoritmo "Conversor2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Daniela Salgado
// Data atual  : 19/11/2025
Var

      angulo, S : real

Inicio

       Escreval("Informe um angulo: ")
       leia(angulo)
       
       S <- Sen(GraupRad(angulo))
       
       Escreval("O Seno de ", angulo, " é igual a ", S)

Fimalgoritmo