Algoritmo "Meu Nome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Daniela Salgado
// Data atual  : 18/11/2025
Var

     nome : caractere

Inicio

     Escreval("Digite seu nome: ")
     leia(nome)
     
     Escreval
     Escreval("Muito prazer!!", nome)

Fimalgoritmo